# Generated by Django 5.0.2 on 2024-04-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customer'},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
