# Generated by Django 5.0.2 on 2024-04-17 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_customer_options_alter_customer_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
