# Generated by Django 5.0.2 on 2024-04-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/company_logos/'),
        ),
    ]
