# Generated by Django 5.0.2 on 2024-04-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_product_category_alter_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/company_logos/'),
        ),
    ]
