# Generated by Django 5.0.2 on 2024-04-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_product_categories_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategory',
            table='product_categories',
        ),
    ]
