# Generated by Django 5.0.2 on 2024-04-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_productcategory_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
    ]
